[package]
name = "libphysicsrender"
version = "0.1.0"
edition = "2021"

[dependencies]
libphysics = { version = "0.1.0", path = "../libphysics" }

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["gfx", "image"]